"use client";
import { type FormEvent } from "react";
import { StitchHeader, StitchIcon } from "./stitch-ui";

type Expense = { solicitudId: string; fecha: string; partida: string; descripcion: string; importe: number; canal: string; ruta: string; unidad: string; observacion: string; origenDinero: string };
export function StitchExpense({ value, onChange, categories, saving, onSubmit, onCancel }: { value: Expense; onChange: (value: Expense) => void; categories: string[]; saving: boolean; onSubmit: (event: FormEvent) => void; onCancel: () => void }) {
  return <form className="sx-form" onSubmit={onSubmit}>
    <StitchHeader title="Rendición de gastos" subtitle="Registra tus gastos y viáticos" icon="receipt"><button type="button" disabled={saving} onClick={onCancel}>Volver</button></StitchHeader>
    <fieldset disabled={saving} className="sx-expense-fields">
      <section className="sx-panel"><label htmlFor="expense-amount">Monto del gasto</label><div className="sx-money-input"><span>S/</span><input id="expense-amount" required type="number" inputMode="decimal" min="0.01" step="0.01" value={value.importe || ""} placeholder="0.00" onChange={e => onChange({ ...value, importe: Number(e.target.value) })}/></div><div className="sx-chips">{[50,100,120,250].map(n => <button type="button" key={n} className={value.importe === n ? "selected" : ""} onClick={() => onChange({ ...value, importe: n })}>{n}</button>)}</div></section>
      <section className="sx-panel"><h3>Categoría del gasto</h3><div className="sx-choice-grid">{categories.map(category => <button type="button" aria-pressed={value.partida === category} className={value.partida === category ? "selected" : ""} key={category} onClick={() => onChange({ ...value, partida: category })}>{category}</button>)}</div><p className="sx-help">Partidas del presupuesto de Gestión financiera.</p>{!categories.length && <p role="status">Cargando partidas presupuestadas…</p>}</section>
      <section className="sx-panel sx-layout"><label>Descripción<input required value={value.descripcion} placeholder="¿En qué se utilizó el dinero?" onChange={e => onChange({ ...value, descripcion: e.target.value })}/></label><div className="sx-form-row"><label>Fecha<input required type="date" value={value.fecha} onChange={e => onChange({ ...value, fecha: e.target.value })}/></label><label>Medio de pago<select value={value.canal} onChange={e => onChange({ ...value, canal: e.target.value })}>{["EFECTIVO","YAPE","PLIN","TRANSFERENCIA","TARJETA"].map(v => <option key={v}>{v}</option>)}</select></label></div><label>Origen del dinero<select value={value.origenDinero} onChange={e => onChange({ ...value, origenDinero: e.target.value })}>{["FONDO DE RUTA","CAJA DE LA EMPRESA","DINERO DEL REPARTIDOR","TARJETA DE LA EMPRESA","OTRO"].map(v => <option key={v}>{v}</option>)}</select></label><label>Vehículo<input value={value.unidad} placeholder="Placa o unidad (opcional)" onChange={e => onChange({ ...value, unidad: e.target.value })}/></label><label>Observaciones<textarea value={value.observacion} placeholder="Detalles adicionales (opcional)" onChange={e => onChange({ ...value, observacion: e.target.value })}/></label></section>
      <p className="sx-alert">El gasto quedará pendiente de aprobación. No se aprobará automáticamente.</p><button className="sx-primary" disabled={saving || !categories.includes(value.partida)}><StitchIcon name="check" size={18}/>{saving ? "Registrando…" : "Registrar gasto"}</button>
    </fieldset>
  </form>;
}
