"use client";
import { type FormEvent } from "react";
import { StitchHeader, StitchIcon } from "./stitch-ui";

type Expense = { solicitudId: string; fecha: string; partida: string; descripcion: string; importe: number; canal: string; ruta: string; unidad: string; observacion: string; origenDinero: string };
export function StitchExpense({ value, onChange, categories, saving, onSubmit, onCancel }: { value: Expense; onChange: (value: Expense) => void; categories: string[]; saving: boolean; onSubmit: (event: FormEvent) => void; onCancel: () => void }) {
  return <form className="sx-form sx-expense-screen" onSubmit={onSubmit}>
    <StitchHeader title="Nueva rendición" subtitle="Registra tus gastos y viáticos" icon="receipt"><span className="sx-expense-status">Pendiente de aprobación</span><button type="button" disabled={saving} onClick={onCancel}>Volver al resumen</button></StitchHeader>
    <fieldset disabled={saving} className="sx-expense-fields">
      <section className="sx-panel sx-expense-amount"><div className="sx-expense-section-title"><label htmlFor="expense-amount">Monto a rendir (PEN)</label><span>Gasto neto + IGV</span></div><div className="sx-expense-amount-row"><div className="sx-money-input"><span>S/</span><input id="expense-amount" required type="number" inputMode="decimal" min="0.01" step="0.01" value={value.importe || ""} placeholder="0.00" onChange={e => onChange({ ...value, importe: Number(e.target.value) })}/></div><div className="sx-expense-quick">{[50,100,120,250].map(n => <button type="button" key={n} className={value.importe === n ? "selected" : ""} onClick={() => onChange({ ...value, importe: n })}>{n}</button>)}</div></div></section>
      <section className="sx-panel sx-expense-category"><div className="sx-expense-section-title"><h3>Categoría del gasto</h3><span>Obligatorio</span></div><div className="sx-choice-grid">{categories.map(category => <button type="button" aria-pressed={value.partida === category} className={value.partida === category ? "selected" : ""} key={category} onClick={() => onChange({ ...value, partida: category })}><StitchIcon name={/combust|gas/i.test(category) ? "truck" : /peaje/i.test(category) ? "arrow" : /manteni|repara/i.test(category) ? "edit" : "receipt"} size={16}/>{category}</button>)}</div><p className="sx-help">Categorías provenientes del presupuesto de Gestión financiera.</p>{!categories.length && <p role="status">Cargando partidas presupuestadas…</p>}</section>
      <section className="sx-panel sx-expense-details"><label>Descripción<input required value={value.descripcion} placeholder="¿En qué se utilizó el dinero?" onChange={e => onChange({ ...value, descripcion: e.target.value })}/></label><div className="sx-form-row"><label>Fecha<input required type="date" value={value.fecha} onChange={e => onChange({ ...value, fecha: e.target.value })}/></label><label>Medio de pago<select value={value.canal} onChange={e => onChange({ ...value, canal: e.target.value })}>{["EFECTIVO","YAPE","PLIN","TRANSFERENCIA","TARJETA"].map(v => <option key={v}>{v}</option>)}</select></label></div><label>Origen del dinero<select value={value.origenDinero} onChange={e => onChange({ ...value, origenDinero: e.target.value })}>{["FONDO DE RUTA","CAJA DE LA EMPRESA","DINERO DEL REPARTIDOR","TARJETA DE LA EMPRESA","OTRO"].map(v => <option key={v}>{v}</option>)}</select></label><div className="sx-form-row"><label>Ruta<input value={value.ruta} placeholder="Jornada o ruta" onChange={e => onChange({ ...value, ruta: e.target.value })}/></label><label>Vehículo<input value={value.unidad} placeholder="Placa o unidad" onChange={e => onChange({ ...value, unidad: e.target.value })}/></label></div><label>Observaciones<textarea value={value.observacion} placeholder="Detalles adicionales (opcional)" onChange={e => onChange({ ...value, observacion: e.target.value })}/></label></section>
      <p className="sx-alert">El gasto quedará pendiente de aprobación. No se aprobará automáticamente.</p><button className="sx-primary sx-expense-submit" disabled={saving || !categories.includes(value.partida)}><StitchIcon name="check" size={18}/>{saving ? "Registrando…" : "Registrar gasto"}</button>
    </fieldset>
  </form>;
}
