"use client";
import { type FormEvent, useEffect, useState } from "react";
import { StitchIcon } from "./stitch-ui";

type Expense = { solicitudId: string; fecha: string; partida: string; descripcion: string; importe: number; canal: string; ruta: string; unidad: string; observacion: string; origenDinero: string; proveedor: string; tipoComprobante: string };
type RecentExpense = { solicitudId: string; partida: string; descripcion: string; importe: number; fecha: string; estadoAprobacion?: string };

export function StitchExpense({ value, onChange, categories, categoriesLoading, saving, onSubmit, canUploadReceipt, receiptFile, onReceiptChange, recent, onSaveDraft }: {
  value: Expense; onChange: (value: Expense) => void; categories: string[]; categoriesLoading: boolean; saving: boolean; onSubmit: (event: FormEvent) => void;
  canUploadReceipt: boolean; receiptFile: File | null; onReceiptChange: (file: File | null) => void; recent: RecentExpense[]; onSaveDraft: () => void;
}) {
  const [preview, setPreview] = useState("");
  useEffect(() => {
    if (!receiptFile || !receiptFile.type.startsWith("image/")) { setPreview(""); return; }
    const url = URL.createObjectURL(receiptFile); setPreview(url); return () => URL.revokeObjectURL(url);
  }, [receiptFile]);
  const chooseFile = (file?: File) => {
    if (!file) return;
    if (!file.type.startsWith("image/") && file.type !== "application/pdf") { onReceiptChange(null); return; }
    onReceiptChange(file);
  };
  return <form className="sx-form sx-expense-screen" onSubmit={onSubmit}>
    <fieldset disabled={saving} className="sx-expense-fields">
      <section className="sx-panel sx-expense-amount"><div className="sx-expense-section-title"><label htmlFor="expense-amount">Monto a rendir (PEN)</label><span>Gasto neto + IGV</span></div><div className="sx-expense-amount-row"><div className="sx-money-input"><span>S/</span><input id="expense-amount" required type="number" inputMode="decimal" min="0.01" step="0.01" value={value.importe || ""} placeholder="0.00" onChange={e => onChange({ ...value, importe: Number(e.target.value) })}/></div><div className="sx-expense-quick">{[50,100,120,250].map(n => <button type="button" key={n} className={value.importe === n ? "selected" : ""} onClick={() => onChange({ ...value, importe: n })}>{n}</button>)}</div></div></section>
      <section className="sx-panel sx-expense-category"><div className="sx-expense-section-title"><h3>Categoría</h3><span>Obligatorio</span></div><div className="sx-choice-grid">{categories.map(category => <button type="button" aria-pressed={value.partida === category} className={value.partida === category ? "selected" : ""} key={category} onClick={() => onChange({ ...value, partida: category })}><StitchIcon name={/combust|gas/i.test(category) ? "truck" : /peaje/i.test(category) ? "arrow" : /manteni|repara/i.test(category) ? "edit" : "receipt"} size={16}/>{category}</button>)}</div>{categoriesLoading ? <p role="status">Cargando presupuesto…</p> : !categories.length && <p className="sx-expense-no-categories" role="status">Este mes no hay partidas de gasto en Gestión financiera. Configura el presupuesto para habilitar el envío.</p>}</section>
      <section className="sx-panel sx-expense-details"><h3 className="sx-expense-block-title">Comprobante y detalle</h3><label>Descripción<input required value={value.descripcion} placeholder="¿En qué se utilizó el dinero?" onChange={e => onChange({ ...value, descripcion: e.target.value })}/></label><div className="sx-form-row"><label>Tipo de comprobante<select value={value.tipoComprobante || "TICKET"} onChange={e => onChange({ ...value, tipoComprobante: e.target.value })}>{["TICKET","BOLETA","FACTURA","RECIBO","SIN COMPROBANTE"].map(v => <option key={v}>{v}</option>)}</select></label><label>Proveedor<input value={value.proveedor || ""} placeholder="Nombre del proveedor" onChange={e => onChange({ ...value, proveedor: e.target.value })}/></label></div><label>Fecha<input required type="date" value={value.fecha} onChange={e => onChange({ ...value, fecha: e.target.value })}/></label><div className="sx-form-row"><label>Medio de pago<select value={value.canal} onChange={e => onChange({ ...value, canal: e.target.value })}>{["EFECTIVO","YAPE","PLIN","TRANSFERENCIA","TARJETA"].map(v => <option key={v}>{v}</option>)}</select></label><label>Origen del dinero<select value={value.origenDinero} onChange={e => onChange({ ...value, origenDinero: e.target.value })}>{["FONDO DE RUTA","CAJA DE LA EMPRESA","DINERO DEL REPARTIDOR","TARJETA DE LA EMPRESA","OTRO"].map(v => <option key={v}>{v}</option>)}</select></label></div><div className="sx-form-row"><label>Ruta<input value={value.ruta} placeholder="Jornada o ruta" onChange={e => onChange({ ...value, ruta: e.target.value })}/></label><label>Vehículo<input value={value.unidad} placeholder="Placa o unidad" onChange={e => onChange({ ...value, unidad: e.target.value })}/></label></div><label>Observaciones<textarea value={value.observacion} placeholder="Detalles adicionales (opcional)" onChange={e => onChange({ ...value, observacion: e.target.value })}/></label>
        <div className="sx-receipt-upload"><div><b>Foto del comprobante</b><small>JPG, PNG o PDF · máximo 2.5 MB</small></div><div className="sx-receipt-actions"><label className="sx-receipt-action">▣ Tomar foto<input type="file" accept="image/*" capture="environment" disabled={!canUploadReceipt || saving} onChange={e => { chooseFile(e.target.files?.[0]); e.currentTarget.value = ""; }}/></label><label className="sx-receipt-action secondary">⇧ Subir archivo<input type="file" accept="image/*,application/pdf" disabled={!canUploadReceipt || saving} onChange={e => { chooseFile(e.target.files?.[0]); e.currentTarget.value = ""; }}/></label></div>{!canUploadReceipt && <small className="sx-receipt-note">La carga de comprobantes requiere conexión con Supabase.</small>}{receiptFile && <div className="sx-receipt-preview">{preview && <img src={preview} alt="Vista previa del comprobante"/>}<span><b>{receiptFile.name}</b><small>{(receiptFile.size / 1024 / 1024).toFixed(2)} MB</small></span><button type="button" aria-label="Quitar comprobante" onClick={() => onReceiptChange(null)}>×</button></div>}</div>
      </section>
      <div className="sx-expense-actions"><button type="button" className="sx-expense-draft" disabled={saving} onClick={onSaveDraft}>Guardar borrador</button><button className="sx-primary sx-expense-submit" disabled={saving || categoriesLoading || !categories.includes(value.partida)}><StitchIcon name="arrow" size={18}/>{saving ? "Enviando…" : "Enviar para aprobación"}</button></div>
      {recent.length > 0 && <details className="sx-expense-recent"><summary>Ver {recent.length} gastos recientes</summary>{recent.map(item => <article key={item.solicitudId}><span><b>{item.partida}</b><small>{item.fecha} · {item.descripcion}</small></span><strong>S/ {Number(item.importe || 0).toFixed(2)}</strong></article>)}</details>}
    </fieldset>
  </form>;
}
