"use client";
import { useState } from "react";
import { StitchHeader, StitchSearch } from "./stitch-ui";
type Movement={fecha?:string;codigo?:string;producto?:string;tipo?:string;cantidad?:number;saldoAnterior?:number;saldoNuevo?:number;observaciones?:string};
export function StitchMovements({rows,products,onRegister,onRefresh,onError}:{rows:Movement[];products:{codigo:string;factorPresentacion?:number;unidad:string}[];onRegister:()=>void;onRefresh:()=>void;onError:(s:string)=>void}) {
 const [query,setQuery]=useState(""),[kind,setKind]=useState("TODOS"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[limit,setLimit]=useState(20);
 const [exporting,setExporting]=useState(false);
 const family=(r:Movement)=>String(r.tipo).includes("AJUSTE") || r.tipo === "MERMA" ? "AJUSTES" : /INGRESO|DEVOLUCION/.test(String(r.tipo)) ? "INGRESOS" : "SALIDAS";
 const filtered=rows.filter(r=>(kind==="TODOS" || family(r)===kind) && `${r.codigo} ${r.producto} ${r.observaciones}`.toLowerCase().includes(query.toLowerCase()) && (!from || String(r.fecha).slice(0,10)>=from) && (!to || String(r.fecha).slice(0,10)<=to));
 const factor=(r:Movement)=>Math.max(1,Number(products.find(p=>p.codigo===r.codigo)?.factorPresentacion || 1));
 async function download(){setExporting(true);try{const XLSX=await import("xlsx");const sheet=XLSX.utils.json_to_sheet(filtered.map(r=>({Fecha:r.fecha,SKU:r.codigo,Producto:r.producto,Tipo:r.tipo,Cantidad_presentaciones:Number(r.cantidad || 0)/factor(r),Factor:factor(r),Cantidad_base:r.cantidad,Saldo_anterior_base:r.saldoAnterior,Saldo_nuevo_base:r.saldoNuevo,Observacion:r.observaciones})));const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,"Movimientos");XLSX.writeFile(book,"NEXA_Movimientos.xlsx");}catch(e){onError(e instanceof Error?e.message:"No se pudo exportar");}finally{setExporting(false);}}
 return <section className="sx-layout sx-movements"><StitchHeader title="Movimientos de inventario" subtitle="Últimos 500 registros · ingresos, salidas y ajustes"><button onClick={onRefresh}>Actualizar</button><button onClick={download} disabled={exporting}>{exporting?"Exportando…":"Excel"}</button><button className="sx-primary" onClick={onRegister}>Registrar</button></StitchHeader><StitchSearch value={query} onChange={setQuery} placeholder="Buscar material, SKU o referencia"/><div className="sx-form-row sx-period-filter"><label>Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><nav className="sx-chips">{["TODOS","INGRESOS","SALIDAS","AJUSTES"].map(k=><button key={k} className={kind===k?"selected":""} onClick={()=>{setKind(k);setLimit(20);}}>{k} · {rows.filter(r=>k==="TODOS" || family(r)===k).length}</button>)}</nav><div className="sx-stock-grid">{filtered.slice(0,limit).map((r,i)=><article className="sx-panel sx-movement" key={`${r.fecha}-${r.codigo}-${i}`}><header><span className={`sx-badge ${family(r)==="INGRESOS"?"green":family(r)==="AJUSTES"?"":"red"}`}>{String(r.tipo).replaceAll("_"," ")}</span><strong>{Number((Number(r.cantidad || 0)/factor(r)).toFixed(4))} {factor(r)>1?`paq. x${factor(r)}`:"und."}</strong></header><h3>{r.producto}</h3><p>{r.codigo} · {r.fecha?new Date(r.fecha).toLocaleString("es-PE",{timeZone:"America/Lima"}):""}</p><p>{r.observaciones || "Sin observaciones"}</p><small>Stock: {Number((Number(r.saldoAnterior || 0)/factor(r)).toFixed(4))} → {Number((Number(r.saldoNuevo || 0)/factor(r)).toFixed(4))} presentaciones</small></article>)}</div>{!filtered.length && <p className="sx-empty">No hay movimientos para estos filtros.</p>}{filtered.length>limit && <button onClick={()=>setLimit(n=>n+20)}>Ver más ({filtered.length-limit})</button>}</section>;
}
