create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create type public.estado_pedido as enum ('POR_COMPRAR','LISTO_PARA_ENTREGA','ENTREGADO','OBSERVADO','ANULADO');
create type public.estado_entrega as enum ('PENDIENTE','EN_RUTA','ENTREGA_COMPLETA','ENTREGA_PARCIAL','CLIENTE_AUSENTE','REPROGRAMADO','RECHAZADO','DIRECCION_INCORRECTA','OTRO');
create type public.estado_cobranza as enum ('NO_APLICA','PENDIENTE_DE_COBRO','COBRANZA_URGENTE','COBRADO');
create type public.estado_boleta as enum ('NO_EMITIDA','EMITIDA','ANULADA');
create type public.estado_gasto as enum ('PENDIENTE_APROBACION','APROBADO','OBSERVADO','RECHAZADO');

create table public.usuarios_perfil (id uuid primary key references auth.users(id) on delete cascade, nombre text not null default '', rol text not null check (rol in ('ADMINISTRADOR','PREVENTISTA','ALMACENERO','REPARTIDOR','FINANZAS')), activo boolean not null default true, legacy_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.clientes (id uuid primary key default gen_random_uuid(), codigo text not null unique, nombre text not null, telefono text, direccion text, correo text, fecha_nacimiento date, observaciones text, estado text not null default 'ACTIVO', legacy_id text, legacy_row integer, legacy_source text default 'SHEETS', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.categorias (id uuid primary key default gen_random_uuid(), nombre text not null unique, activo boolean not null default true, legacy_id text, created_at timestamptz not null default now());
create table public.marcas (id uuid primary key default gen_random_uuid(), nombre text not null unique, activo boolean not null default true, legacy_id text, created_at timestamptz not null default now());
create table public.proveedores (id uuid primary key default gen_random_uuid(), codigo text unique, nombre text not null, documento text, telefono text, estado text not null default 'ACTIVO', legacy_id text, created_at timestamptz not null default now());
create table public.vehiculos (id uuid primary key default gen_random_uuid(), placa text not null unique, descripcion text, estado text not null default 'ACTIVO', legacy_id text, created_at timestamptz not null default now());
create table public.almacenes (id uuid primary key default gen_random_uuid(), codigo text not null unique, nombre text not null, direccion text, activo boolean not null default true, created_at timestamptz not null default now());
create table public.productos (id uuid primary key default gen_random_uuid(), codigo text not null unique, nombre text not null, categoria_id uuid references public.categorias(id), marca_id uuid references public.marcas(id), unidad_base text not null default 'UND', costo_actual numeric(16,4) not null default 0, precio_venta numeric(16,4) not null default 0, permite_fraccionamiento boolean not null default false, activo boolean not null default true, legacy_id text, legacy_row integer, legacy_source text default 'SHEETS', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.presentaciones (id uuid primary key default gen_random_uuid(), producto_id uuid not null references public.productos(id), nombre text not null, factor numeric(16,4) not null check (factor > 0), precio numeric(16,4) not null default 0, permite_fraccionamiento boolean not null default false, fracciones_permitidas numeric(8,4)[] not null default '{}', es_compra boolean not null default false, es_venta boolean not null default true, activo boolean not null default true, legacy_id text, unique(producto_id,nombre));

create table public.pedidos (id uuid primary key default gen_random_uuid(), codigo_pedido text not null unique, cliente_id uuid not null references public.clientes(id), fecha timestamptz not null default now(), subtotal numeric(16,2) not null default 0, descuento numeric(16,2) not null default 0, total numeric(16,2) not null default 0, estado_operativo public.estado_pedido not null default 'POR_COMPRAR', estado_entrega public.estado_entrega not null default 'PENDIENTE', estado_cobranza public.estado_cobranza not null default 'NO_APLICA', estado_boleta public.estado_boleta not null default 'NO_EMITIDA', observaciones text, usuario_creacion uuid references auth.users(id), legacy_id text, legacy_row integer, legacy_source text default 'SHEETS', idempotency_key text unique, version integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.pedido_detalle (id uuid primary key default gen_random_uuid(), pedido_id uuid not null references public.pedidos(id), producto_id uuid not null references public.productos(id), presentacion_id uuid references public.presentaciones(id), cantidad_presentacion numeric(16,4) not null, fraccion numeric(8,4) not null default 0, factor_presentacion numeric(16,4) not null, cantidad_unidades_base numeric(16,4) not null, precio_presentacion numeric(16,4) not null, precio_aplicado numeric(16,4) not null, subtotal numeric(16,2) not null, legacy_id text, unique(pedido_id,producto_id,presentacion_id));
create table public.pedido_historial_estado (id uuid primary key default gen_random_uuid(), pedido_id uuid not null references public.pedidos(id), tipo_estado text not null, estado_anterior text, estado_nuevo text not null, observacion text, usuario_id uuid references auth.users(id), created_at timestamptz not null default now());

create table public.stock_actual (producto_id uuid not null references public.productos(id), almacen_id uuid not null references public.almacenes(id), stock_fisico numeric(16,4) not null default 0, stock_reservado numeric(16,4) not null default 0, stock_en_ruta numeric(16,4) not null default 0, stock_disponible numeric(16,4) generated always as (stock_fisico-stock_reservado-stock_en_ruta) stored, updated_at timestamptz not null default now(), primary key(producto_id,almacen_id), check(stock_fisico>=0 and stock_reservado>=0 and stock_en_ruta>=0 and stock_fisico-stock_reservado-stock_en_ruta>=0));
create table public.movimientos_inventario (id uuid primary key default gen_random_uuid(), producto_id uuid not null references public.productos(id), almacen_id uuid not null references public.almacenes(id), tipo_movimiento text not null check(tipo_movimiento in ('INGRESO_COMPRA','SALIDA_ENTREGA','RESERVA','LIBERACION_RESERVA','DEVOLUCION','AJUSTE_POSITIVO','AJUSTE_NEGATIVO','TRANSFERENCIA','MERMA','MOVER_A_RUTA')), cantidad numeric(16,4) not null check(cantidad>0), referencia_tipo text, referencia_id uuid, saldo_anterior numeric(16,4) not null, saldo_nuevo numeric(16,4) not null, usuario_id uuid references auth.users(id), idempotency_key text not null unique, created_at timestamptz not null default now(), observacion text, legacy_id text, legacy_row integer);
create table public.reservas_stock (id uuid primary key default gen_random_uuid(), pedido_id uuid not null references public.pedidos(id), producto_id uuid not null references public.productos(id), almacen_id uuid not null references public.almacenes(id), cantidad numeric(16,4) not null check(cantidad>0), estado text not null check(estado in ('RESERVADA','EN_RUTA','CONSUMIDA','LIBERADA')), idempotency_key text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.recepciones (id uuid primary key default gen_random_uuid(), codigo text not null unique, proveedor_id uuid references public.proveedores(id), fecha timestamptz not null default now(), estado text not null default 'REGISTRADA', usuario_id uuid references auth.users(id), legacy_id text);
create table public.recepcion_detalle (id uuid primary key default gen_random_uuid(), recepcion_id uuid not null references public.recepciones(id), producto_id uuid not null references public.productos(id), cantidad_base numeric(16,4) not null, costo_unitario numeric(16,4) not null);
create table public.ajustes_inventario (id uuid primary key default gen_random_uuid(), producto_id uuid not null references public.productos(id), almacen_id uuid not null references public.almacenes(id), cantidad numeric(16,4) not null, motivo text not null, estado text not null default 'APLICADO', usuario_id uuid references auth.users(id), created_at timestamptz not null default now());

create table public.jornadas (id uuid primary key default gen_random_uuid(), fecha date not null, repartidor_id uuid references auth.users(id), vehiculo_id uuid references public.vehiculos(id), ruta text, estado text not null default 'ABIERTA' check(estado in ('ABIERTA','EN_RENDICION','CERRADA','OBSERVADA')), created_at timestamptz not null default now(), closed_at timestamptz, unique(fecha,repartidor_id,vehiculo_id));
create table public.jornada_pedidos (jornada_id uuid not null references public.jornadas(id), pedido_id uuid not null references public.pedidos(id), orden_visita integer not null default 0, estado text not null default 'ASIGNADO', primary key(jornada_id,pedido_id));
create table public.entregas (id uuid primary key default gen_random_uuid(), pedido_id uuid not null references public.pedidos(id), jornada_id uuid references public.jornadas(id), estado public.estado_entrega not null, fecha_entrega timestamptz, repartidor_id uuid references auth.users(id), observacion text, idempotency_key text not null unique, created_at timestamptz not null default now());
create table public.entrega_detalle (id uuid primary key default gen_random_uuid(), entrega_id uuid not null references public.entregas(id), producto_id uuid not null references public.productos(id), cantidad_pedida numeric(16,4) not null, cantidad_entregada numeric(16,4) not null, cantidad_pendiente numeric(16,4) generated always as (cantidad_pedida-cantidad_entregada) stored, check(cantidad_entregada>=0 and cantidad_entregada<=cantidad_pedida));
create table public.evidencias_entrega (id uuid primary key default gen_random_uuid(), entrega_id uuid not null references public.entregas(id), storage_path text not null, tipo text not null, created_at timestamptz not null default now());

create table public.pagos (id uuid primary key default gen_random_uuid(), pedido_id uuid not null references public.pedidos(id), cliente_id uuid not null references public.clientes(id), fecha timestamptz not null default now(), monto numeric(16,2) not null check(monto>0), estado text not null default 'APLICADO', usuario_id uuid references auth.users(id), idempotency_key text not null unique, created_at timestamptz not null default now(), legacy_id text);
create table public.pago_detalle (id uuid primary key default gen_random_uuid(), pago_id uuid not null references public.pagos(id), medio text not null check(medio in ('EFECTIVO','YAPE','PLIN','TRANSFERENCIA','OTRO')), monto numeric(16,2) not null check(monto>0), referencia text);
create table public.compromisos_pago (id uuid primary key default gen_random_uuid(), pedido_id uuid not null references public.pedidos(id), fecha_compromiso date not null, medio text, observacion text, estado text not null default 'PENDIENTE', created_at timestamptz not null default now());
create table public.gestiones_cobranza (id uuid primary key default gen_random_uuid(), pedido_id uuid not null references public.pedidos(id), tipo text not null, resultado text, observacion text, usuario_id uuid references auth.users(id), created_at timestamptz not null default now());

create table public.gastos (id uuid primary key default gen_random_uuid(), fecha date not null, categoria text not null, subcategoria text, descripcion text not null, monto numeric(16,2) not null check(monto>0), medio_pago text, origen_dinero text, jornada_id uuid references public.jornadas(id), vehiculo_id uuid references public.vehiculos(id), repartidor_id uuid references auth.users(id), proveedor text, comprobante_url text, estado public.estado_gasto not null default 'PENDIENTE_APROBACION', usuario_id uuid references auth.users(id), idempotency_key text unique, legacy_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.rendiciones (id uuid primary key default gen_random_uuid(), jornada_id uuid not null unique references public.jornadas(id), efectivo_esperado numeric(16,2) not null, efectivo_rendido numeric(16,2) not null, diferencia numeric(16,2) not null, observacion text, estado text not null, usuario_id uuid references auth.users(id), created_at timestamptz not null default now());
create table public.cuentas_financieras (id uuid primary key default gen_random_uuid(), codigo text not null unique, nombre text not null, tipo text not null, activo boolean not null default true);
create table public.movimientos_financieros (id uuid primary key default gen_random_uuid(), fecha date not null, tipo text not null, categoria text not null, concepto text, monto numeric(16,2) not null, cuenta_id uuid references public.cuentas_financieras(id), referencia_tipo text, referencia_id uuid, usuario_id uuid references auth.users(id), created_at timestamptz not null default now());
create table public.presupuestos (id uuid primary key default gen_random_uuid(), anio integer not null, mes integer not null check(mes between 1 and 12), objetivo_ventas numeric(16,2) not null default 0, estado text not null default 'BORRADOR', created_at timestamptz not null default now(), unique(anio,mes));
create table public.presupuesto_detalle (id uuid primary key default gen_random_uuid(), presupuesto_id uuid not null references public.presupuestos(id), categoria text not null, partida text not null, monto numeric(16,2) not null, unique(presupuesto_id,categoria,partida));
create table public.objetivos (id uuid primary key default gen_random_uuid(), nombre text not null, monto numeric(16,2) not null, fecha_objetivo date, prioridad text, estado text not null default 'ACTIVO', created_at timestamptz not null default now());
create table public.proyecciones (id uuid primary key default gen_random_uuid(), anio integer not null, mes integer not null, periodo smallint not null check(periodo in (1,2,3)), indicador text not null, valor numeric(16,2) not null, created_at timestamptz not null default now(), unique(anio,mes,periodo,indicador));
create table public.metas_periodo (id uuid primary key default gen_random_uuid(), anio integer not null, mes integer not null, periodo smallint not null check(periodo in (1,2)), fecha_inicio date not null, fecha_fin date not null, meta numeric(16,2) not null, unique(anio,mes,periodo));

create table public.eventos (id uuid primary key default gen_random_uuid(), tipo text not null, entidad text not null, entidad_id uuid, descripcion text not null, importe numeric(16,2) not null default 0, usuario_id uuid references auth.users(id), created_at timestamptz not null default now(), metadata jsonb not null default '{}');
create table public.auditoria (id uuid primary key default gen_random_uuid(), tabla text not null, registro_id uuid, accion text not null, estado_anterior jsonb, estado_nuevo jsonb, usuario_id uuid references auth.users(id), created_at timestamptz not null default now());
create table public.configuracion (clave text primary key, valor jsonb not null, updated_at timestamptz not null default now(), updated_by uuid references auth.users(id));

insert into public.almacenes(codigo,nombre) values ('PRINCIPAL','Almacén principal') on conflict do nothing;
